import Head from 'next/head';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create next app</title>
        <meta name="description" content="Generated by next app" />
      </Head>

      <h1 className="text-xl font-bold text-blue-500">Tailwind</h1>
    </div>
  );
}
